### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by sleepypioneer**

### CODE REVIEW

**Comment by sleepypioneer** [comment]
I am not totally sure how I get this from here to updating the actual circle ci images -> looking into it now

**Review by emilywoods — APPROVED** [review]
:badger:

**Comment by sleepypioneer** [comment]
going to try https://github.com/ecosia/circleci-images/pull/44 first

**Review by pbabbicola — APPROVED** [review]

**Comment by sleepypioneer** [comment]
@pbabbicola can we look at this on maintenance day? This actually is the image used for most our services in core, the search one was a different dockerfile. I'm thinking in general it's worth updating them all but would rather think about it again on Thursday :D

**Comment by pbabbicola** [comment]
> @pbabbicola can we look at this on maintenance day? This actually is the image used for most our services in core, the search one was a different dockerfile. I'm thinking in general it's worth updating them all but would rather think about it again on Thursday :D

yusss

**Pull request merged**
